version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=Practice_2
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}